### ISSUE TITLE
boto.codedeploy.exceptions.DeploymentLimitExceededException

### ISSUE THREAD

**Issue by cxmcc** [instacart/instacart-software-center#4]
isc should probably catch the above exception and re-raise as a known custom error.
what do you think?

boto.codedeploy.exceptions.DeploymentLimitExceededException: DeploymentLimitExceededException: 400 Bad Request
{u'message': u"Deployment Group 'a6d42e1e-ec50-4a59-8250-5c3a9fa8a1cf' is already deploying deployment 'd-732HRRGX8'", u'__type': u'DeploymentLimitExceededException'}

**Comment by solidsnack** [comment]
I think you're right. So now we'll be following the "error with errors" pattern.
